name: unity-cv-dog-detection
channels:
  - defaults
  - pytorch
  - torchvision
dependencies:
  - pip==21.2.4
  - python=3.8
  - pytorch==1.8
  - torchvision=0.9.0
  - flake8=3.8.3
  - isort=4.3.21
  - protobuf=3.17.2
  - pytest=6.2.3
  - pytest-cov=2.10.0
  - pip:
    - git+https://github.com/facebookresearch/detectron2.git
