estimator: Detectron
backbone: resnet50
num_classes: 1
task: dog_detection
train:
  dataset:
    name: synth_0_1
    synth: True
  transfer_learning:
    enabled: True
    checkpoint: detectron2://ImageNetPretrained/MSRA/R-50.pkl #Transfer learning checkpoint

test:
  dataset:
    name: real_images
    synth: False
  checkpoint: ckpt/20220126-121925/model_final.pth  # COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml # Evaluation checkpoint
  results: gs://doc-detection/results

model:
  workers: 4
  gpu: 8
  IMS_PER_BATCH: 16
  base_lr: 0.0025
  MAX_ITER: 270000
  resume: False
  REFERENCE_WORLD_SIZE: 8
  FREEZE_AT: 0
  BATCH_SIZE_PER_IMAGE: 128
  NUM_CLASSES: 1
  EVAL_PERIOD: 5000
  CHECKPOINT_PERIOD: 10000
  STEPS: (210000, 250000)
  config_yaml: faster_rcnn_R_50_FPN_3x.yaml
