estimator: Detectron
backbone: resnet50
num_classes: 1
task: dog_detection
train:
  dataset:
    name: Datamaker_indoor_dog
    data_split: dev # synth, dev, train, val
    synth: True
    location: gs://doc-detection/dataset/synth/dogs_5000.zip #synthetic/aad646cc-343e-4e66-b907-4e443f94dbd8.zip  #
  transfer_learning:
    enabled: True
    checkpoint: COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml

test:
  dataset:
    name: Real_images
    data_split: val
    synth: False
  checkpoint: output/model_final.pth  # COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml # Evaluation checkpoint
  results: gs://doc-detection/results

model:
  workers: 1
  gpu: 0
  IMS_PER_BATCH: 16
  base_lr: 0.00025
  MAX_ITER: 170000
  resume: True
  REFERENCE_WORLD_SIZE: 1
  FREEZE_AT: 0
  BATCH_SIZE_PER_IMAGE: 128
  NUM_CLASSES: 1
  CHECKPOINT_PERIOD: 10000
  STEPS: (110000, 150000)
  EVAL_PERIOD: 5000
  TTA_ENABLED: False
  config_yaml: faster_rcnn_R_50_FPN_3x.yaml
